'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
export default function Admin(){
 const [me,setMe]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[courses,setCourses]=useState<any[]>([]),[enrollments,setEnrollments]=useState<any[]>([]),[lessons,setLessons]=useState<any[]>([]);
 const [q,setQ]=useState(''),[msg,setMsg]=useState(''),[selectedCourse,setSelectedCourse]=useState('');
 const [form,setForm]=useState<any>({isFree:true,published:false}),[lessonForm,setLessonForm]=useState<any>({published:true,position:1});
 const load=async()=>{const m=await fetch('/api/auth/me').then(r=>r.json());setMe(m.user);if(m.user?.role!=='admin')return;const [u,c,e]=await Promise.all([fetch('/api/admin/users?q='+encodeURIComponent(q)).then(r=>r.json()),fetch('/api/admin/courses').then(r=>r.json()),fetch('/api/admin/enrollments').then(r=>r.json())]);setUsers(u.users||[]);setCourses(c.courses||[]);setEnrollments(e.enrollments||[])};
 const loadLessons=async(id:string)=>{setSelectedCourse(id);if(!id){setLessons([]);return}const r=await fetch('/api/admin/lessons?courseId='+id);const j=await r.json();setLessons(j.lessons||[])};
 useEffect(()=>{load()},[]);
 const grant=async(userId:string,courseId:string)=>{const r=await fetch('/api/admin/enrollments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,courseId})});setMsg(r.ok?'Access granted.':'Could not grant access.');load()};
 const revoke=async(userId:string,courseId:string)=>{const r=await fetch('/api/admin/enrollments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,courseId})});setMsg(r.ok?'Access revoked.':'Could not revoke access.');load()};
 const createCourse=async()=>{const r=await fetch('/api/admin/courses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:form.isFree?0:Number(form.price||0)})});const j=await r.json();setMsg(r.ok?'Playlist created.':j.error||'Could not create playlist.');if(r.ok)setForm({isFree:true,published:false});load()};
 const uploadFile=async(file:File)=>{const r=await fetch('/api/admin/upload/presign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,type:file.type,size:file.size})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not prepare upload');const put=await fetch(j.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});if(!put.ok)throw new Error('Upload failed');return j};
 const createLesson=async()=>{try{let media:any={};if(lessonForm.file){setMsg('Uploading lesson file…');media=await uploadFile(lessonForm.file)}const payload={...lessonForm,courseId:selectedCourse,file:undefined,fileUrl:media.url||null,fileName:media.name||lessonForm.file?.name||null,published:true};const r=await fetch('/api/admin/lessons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setMsg(r.ok?'Lesson added to playlist.':j.error||'Could not create lesson.');if(r.ok)setLessonForm({published:true,position:lessons.length+2});loadLessons(selectedCourse)}catch(e:any){setMsg(e.message||'Upload failed.')}};
 if(me===null)return <main><div className="shell"><div className="section"><p className="muted">Checking administrator session…</p></div></div></main>;
 if(me.role!=='admin')return <main><div className="shell"><div className="section"><div className="error">Administrator access required.</div><Link className="btn" href="/">Back</Link></div></div></main>;
 return <main><div className="shell"><nav className="nav"><Link className="brand" href="/">MARWAN<span>.SWEDAN</span></Link><div className="navlinks"><Link href="/courses">Academy</Link><Link href="/">Portfolio</Link></div><button className="btn" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'}}>Sign out</button></nav><section className="dash"><div className="eyebrow">Creator Console</div><h1 style={{fontFamily:'Space Grotesk',fontSize:52,margin:'12px 0'}}>Build the academy.</h1><p className="muted" style={{maxWidth:680}}>A course is a playlist. Create it here, choose free or paid, set the price, then add lessons and upload videos/files directly from your device.</p>{msg&&<div className="success" style={{marginTop:18}}>{msg}</div>}
 <div className="card" style={{margin:'25px 0'}}><h3>Create playlist</h3><div className="grid"><div>{['title','slug','description','category','level'].map(k=><div className="field" key={k}><label>{k}</label>{k==='description'?<textarea value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</div>)}<div className="field"><label>Total duration in minutes</label><input type="number" value={form.durationMinutes||0} onChange={e=>setForm({...form,durationMinutes:Number(e.target.value)})}/></div></div><div><div className="field"><label>Access</label><select value={form.isFree?'free':'paid'} onChange={e=>setForm({...form,isFree:e.target.value==='free'})}><option value="free">Free</option><option value="paid">Paid</option></select></div>{!form.isFree&&<div className="field"><label>Price · EGP</label><input type="number" min="1" step="0.01" value={form.price||''} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div>}<div className="field"><label>Publish</label><select value={form.published?'yes':'no'} onChange={e=>setForm({...form,published:e.target.value==='yes'})}><option value="no">Save as draft</option><option value="yes">Publish</option></select></div><button className="btn primary" onClick={createCourse}>Create playlist</button></div></div></div>
 <div className="card" style={{marginBottom:25}}><h3>Playlist lessons</h3><div className="field"><label>Playlist</label><select value={selectedCourse} onChange={e=>loadLessons(e.target.value)}><option value="">Select playlist</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></div>{selectedCourse&&<><div className="grid"><div><div className="field"><label>Lesson title</label><input value={lessonForm.title||''} onChange={e=>setLessonForm({...lessonForm,title:e.target.value})}/></div><div className="field"><label>Lesson slug</label><input value={lessonForm.slug||''} onChange={e=>setLessonForm({...lessonForm,slug:e.target.value})}/></div><div className="field"><label>Lesson duration · minutes</label><input type="number" value={lessonForm.durationMinutes||0} onChange={e=>setLessonForm({...lessonForm,durationMinutes:Number(e.target.value)})}/></div></div><div><div className="field"><label>Video / file from device</label><input type="file" accept="video/*,audio/*,.pdf,.zip,.rar,.txt,.md,.doc,.docx,.ppt,.pptx" onChange={e=>setLessonForm({...lessonForm,file:e.target.files?.[0]||null})}/><span className="small muted">Large files go directly to storage instead of through the app server.</span></div><div className="field"><label>Optional video URL</label><input value={lessonForm.videoUrl||''} onChange={e=>setLessonForm({...lessonForm,videoUrl:e.target.value})}/></div></div></div><div className="field"><label>Lesson notes</label><textarea value={lessonForm.content||''} onChange={e=>setLessonForm({...lessonForm,content:e.target.value})}/></div><button className="btn primary" onClick={createLesson}>Add lesson</button>{lessons.map(l=><div className="lesson" key={l.id}><div><b>{l.position}. {l.title}</b><div className="small muted">{l.duration_minutes} min {l.file_name?'· '+l.file_name:''}</div></div></div>)}</>}</div>
 <div className="card" style={{margin:'25px 0',overflowX:'auto'}}><h3>User access</h3><div className="actions"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="name, email or username" style={{flex:1,minWidth:240}}/><button className="btn" onClick={load}>Search</button></div><table className="table"><thead><tr><th>User</th><th>Contact</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b><br/><span className="small muted">@{u.username}</span></td><td>{u.email}<br/>{u.whatsapp}</td><td><a className="btn" href={`https://wa.me/${u.whatsapp}`} target="_blank">WhatsApp</a><select style={{marginLeft:7}} defaultValue="" onChange={e=>{if(e.target.value)grant(u.id,e.target.value)}}><option value="">Grant playlist…</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></td></tr>)}</tbody></table></div>
 <div className="card"><h3>Active access</h3>{enrollments.length===0?<p className="muted">No enrollments yet.</p>:enrollments.map(e=><div className="lesson" key={e.id}><div><b>{e.name}</b><div className="small muted">{e.course_title}</div></div><button className="btn" onClick={()=>revoke(e.user_id,e.course_id)}>Revoke</button></div>)}</div>
 </section></div></main>}