import Link from 'next/link';

const skills=['Incident Response','SIEM Architecture','Threat Hunting','Memory Forensics','Network Traffic Analysis','Alert Triage','Phishing Analysis','Log Correlation','Wazuh','Wireshark','Volatility','Autopsy','Python / FastAPI','C++','JavaScript','SQL','TCP/IP','Linux Administration'];
const roles=[['Jul 2026 — Present','Security Operations Center Analyst','Alignerr','24/7 security event monitoring, real-time alert triage, threat analysis and incident-response runbooks.'],['Jul 2026 — Present','Information Security Intern','Commercial International Bank (CIB Egypt)','Corporate banking defense procedures, security policy review, risk governance, vulnerability outputs and access-log auditing.'],['Jun 2026 — Present','Network Engineer (Contract)','Internet Society','Routing topologies, protocol resilience, infrastructure blueprints and secure routing working groups.'],['Feb 2026 — Present','CTF Player & Digital Forensics Analyst','Information Technology Institute','Top 27 digital forensics investigators and CTF players across Egypt in 2026, with memory, filesystem and PCAP triage.'],['Apr 2026 — Present','Founder & Chairman','Sudo Academy','Built a technical volunteering academy and mentored 150+ students across cybersecurity, networks and programming.'],['Apr 2026 — May 2026','Cyber Security Instructor','Pharos University in Alexandria','Instructed 15+ high-performing students for the official university CTF competition.']];
const projects=[['Artifact Hunter','Digital Forensics & Triage Engine','Python, FastAPI, Volatility, Wireshark','Automated triage engine for RAM images and PCAP artifacts with modular REST endpoints.'],['Smart Environmental Regulation & Embedded Robotic Platform','Embedded systems','C++, Embedded C, Arduino UNO, Sensors','Autonomous cooling controller and 4WD robot with serial telemetry.'],['Optimized Database Application Framework','Web platform','JavaScript, HTML5, CSS3, SQL','Modular platform optimized for fast structured querying over relational schemas.']];
const certs=['LetsDefend — SOC Member','Netriders — System Operator Certification (SOC)','Netriders — Digital Forensics Fundamentals','Basel Institute on Governance — OSINT','ITI — Global Cyber Championship CTF','IBM — Incident Response & Digital Forensics','MaharaTech — Incident Handling & Response','MaharaTech — Digital Forensics and Investigations','MaharaTech — Advanced Digital Forensics','MaharaTech — Memory and Network Traffic','MaharaTech — Digital Forensics Investigator','MaharaTech — Network Forensics Track','MaharaTech — CEH Track','MaharaTech — Cybersecurity Foundation','Cisco — Introduction to Cybersecurity','Cisco — Network Basics','MaharaTech — Network Security','MaharaTech — Computer Network Fundamentals','MaharaTech — RHCSA Track','MaharaTech — Python Programming Basics','Cisco — Python Essentials 1','Microsoft — AI Tools'];
export default function Home(){return <main><div className="shell"><nav className="nav"><Link className="brand" href="/">MARWAN.SWEDAN</Link><div className="navlinks"><a href="#work">Work</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#academy">Academy</a></div><div className="actions" style={{margin:0}}><Link className="btn ghost" href="/login">Sign in</Link><Link className="btn primary" href="/register">Join Academy</Link></div></nav>
<section className="hero"><div><div className="eyebrow">Cybersecurity • Digital Forensics • SOC</div><h1>Security is a discipline.<br/><span>So is the craft.</span></h1><p>Cybersecurity Analyst and digital-forensics practitioner focused on security operations, incident response, forensic triage and practical technical education.</p><div className="actions"><a className="btn primary" href="#academy">Explore Academy</a><a className="btn" href="#work">View experience</a></div></div><div className="portrait"><img src="/profile.svg" alt="Marwan Swedan profile"/></div></section>
<div className="metrics"><div className="metric"><b>Top 27</b><span>Digital Forensics / CTF in Egypt, ITI 2026</span></div><div className="metric"><b>150+</b><span>Students mentored through Sudo Academy</span></div><div className="metric"><b>3.77/4</b><span>Outstanding cumulative GPA at PUA</span></div></div>
<section id="skills" className="section"><div className="sectionhead"><div><div className="eyebrow">Capabilities</div><h2>Built for defensive work.</h2></div><p className="muted">A practical stack spanning monitoring, forensics, programming and infrastructure.</p></div><div className="chips">{skills.map(x=><span className="chip" key={x}>{x}</span>)}</div></section>
<section id="work" className="section"><div className="sectionhead"><div><div className="eyebrow">Experience</div><h2>Where the work happens.</h2></div></div><div className="timeline">{roles.map(r=><div className="role" key={r[1]+r[2]}><time>{r[0]}</time><div><h3>{r[1]} · {r[2]}</h3><p>{r[3]}</p></div></div>)}</div></section>
<section id="projects" className="section"><div className="sectionhead"><div><div className="eyebrow">Selected projects</div><h2>From evidence to systems.</h2></div></div><div className="grid">{projects.map(p=><article className="card" key={p[0]}><span className="tag">{p[1]}</span><h3>{p[0]}</h3><p>{p[3]}</p><div className="chips">{p[2].split(', ').map(t=><span className="chip" key={t}>{t}</span>)}</div></article>)}</div></section>
<section id="academy" className="section"><div className="sectionhead"><div><div className="eyebrow">Private Academy</div><h2>Learn the way defenders think.</h2></div><Link className="btn primary" href="/courses">Open Courses</Link></div><div className="grid"><article className="card"><span className="tag">SOC</span><h3>SOC Analyst Foundations</h3><p>Alert triage, SIEM thinking, false positives, IOCs and incident response.</p></article><article className="card"><span className="tag">Forensics</span><h3>Digital Forensics Fundamentals</h3><p>Evidence handling, artifacts, memory analysis and PCAP triage.</p></article><article className="card"><span className="tag">Programming</span><h3>Python for Cybersecurity</h3><p>Automation, parsing, APIs and defensive scripting workflows.</p></article></div></section>
<section className="section"><div className="sectionhead"><div><div className="eyebrow">Credentials</div><h2>Verified learning footprint.</h2></div></div><div className="grid">{certs.map(c=><div className="card" key={c}><span className="tag">Credential</span><h3>{c}</h3></div>)}</div></section>
<footer className="footer"><div>© 2026 Marwan Swedan · Cybersecurity Analyst · Digital Forensics · SOC</div></footer></div></main>}