import Link from 'next/link';
import {redirect} from 'next/navigation';
import {session} from '@/lib/auth';
import LogoutButton from '@/app/components/LogoutButton';

const roles=[['Jul 2026 — Present','Security Operations Center Analyst','Alignerr'],['Jul 2026 — Present','Information Security Intern','Commercial International Bank (CIB Egypt)'],['Jun 2026 — Present','Network Engineer (Contract)','Internet Society'],['Feb 2026 — Present','CTF Player & Digital Forensics Analyst','Information Technology Institute'],['Apr 2026 — Present','Founder & Chairman','Sudo Academy']];
const projects=[['Artifact Hunter','Digital Forensics','Python · FastAPI · Volatility · Wireshark'],['Smart Environmental Regulation & Embedded Robotic Platform','Embedded Systems','C++ · Embedded C · Arduino'],['Optimized Database Application Framework','Web Platform','JavaScript · SQL · HTML · CSS']];
const featuredCerts=['LetsDefend — SOC Member','Netriders — Digital Forensics Fundamentals','IBM — Incident Response & Digital Forensics','ITI — Global Cyber Championship CTF','Cisco — Introduction to Cybersecurity'];
export default async function Home(){const user=await session();if(!user)redirect('/login');return <main><div className="shell"><nav className="nav"><Link className="brand" href="/">Marwan <span>Swedan</span></Link><div className="navlinks"><Link href="/">Home</Link><Link href="/courses">Academy</Link><a href="#work">Experience</a><a href="#projects">Projects</a><Link href="/account">Account</Link></div><div className="actions" style={{margin:0}}><Link className="btn desktopOnly" href="/account">@{user.username}</Link>{user.role==='admin'&&<Link className="btn primary desktopOnly" href="/admin">Dashboard</Link>}<span className="desktopOnly"><LogoutButton/></span></div><details className="mobileMenu"><summary aria-label="Open navigation menu"><span></span><span></span><span></span></summary><div className="mobileMenuPanel"><Link href="/">Home</Link><Link href="/courses">Academy</Link><a href="#work">Experience</a><a href="#projects">Projects</a><Link href="/account">@{user.username}</Link>{user.role==='admin'&&<Link className="mobileMenuAdmin" href="/admin">Dashboard</Link>}<LogoutButton mobile/></div></details></nav>
<section className="hero"><div className="heroCopy"><div className="eyebrow">Marwan Swedan Academy · Cybersecurity</div><h1>Build your skills.<br/><span>Secure your future.</span></h1><p>Practical cybersecurity education, digital forensics and real technical projects — built around skills you can actually use.</p><div className="actions"><Link className="btn primary" href="/courses">Explore courses →</Link><a className="btn" href="#work">View portfolio</a></div><div className="heroNote">CEO & Founder · Cybersecurity · Digital Forensics · SOC · Programming</div></div><div className="heroVisual"><div className="heroMark">MS</div><div className="heroYear">CEO · FOUNDER · 2026</div></div></section>
<section className="signature"><div><b>Cybersecurity</b><span>SOC operations & threat analysis</span></div><div><b>Forensics</b><span>Digital evidence & investigation</span></div><div><b>Academy</b><span>Practical courses & guided learning</span></div></section>
<section className="section compact"><div className="sectionhead"><div><div className="eyebrow">The academy</div><h2>Learn by building. Learn by doing.</h2></div><Link className="btn" href="/courses">All courses →</Link></div><div className="projectGrid"><article className="projectCard"><span>01 · Learn</span><h3>Expert-led courses</h3><p>Structured lessons designed around practical cybersecurity skills, not filler.</p></article><article className="projectCard"><span>02 · Practice</span><h3>Real projects</h3><p>Build work you can understand, test and eventually show in your portfolio.</p></article><article className="projectCard"><span>03 · Grow</span><h3>Security mindset</h3><p>From fundamentals to investigation, analysis and defensive thinking.</p></article></div></section>
<section id="work" className="section compact"><div className="sectionhead"><div><div className="eyebrow">Portfolio · short version</div><h2>What I do outside the academy.</h2></div></div><div className="timeline">{roles.map(r=><div className="role" key={r[1]+r[2]}><time>{r[0]}</time><div><h3>{r[1]}</h3><p>{r[2]}</p></div></div>)}</div></section>
<section id="projects" className="section compact"><div className="sectionhead"><div><div className="eyebrow">Selected work</div><h2>Built, tested, investigated.</h2></div></div><div className="projectGrid">{projects.map(p=><article className="projectCard" key={p[0]}><span>{p[1]}</span><h3>{p[0]}</h3><p>{p[2]}</p><div className="projectArrow">↗</div></article>)}</div></section>
<section className="academyBanner"><div><div className="eyebrow">Marwan Swedan Academy</div><h2>Your next skill starts here.</h2><p>Browse the current courses, open a playlist you have access to, or contact me about a paid course.</p></div><Link className="btn primary" href="/courses">Enter the academy →</Link></section>
<section className="section compact"><div className="sectionhead"><div><div className="eyebrow">Credentials</div><h2>Selected highlights.</h2></div></div><div className="certRow">{featuredCerts.map(c=><div className="cert" key={c}>{c}<span>↗</span></div>)}</div></section>
<footer className="footer"><div><div className="brand">Marwan <span>Swedan</span></div><p>CEO & Founder · Marwan Swedan Academy</p><p>Cybersecurity · Digital Forensics · Academy</p></div><div><h4>Explore</h4><Link href="/">Home</Link><Link href="/courses">Academy</Link><Link href="/account">My account</Link>{user.role==='admin'&&<Link href="/admin">Dashboard</Link>}</div><div><h4>Connect</h4><a href="https://www.linkedin.com/in/marwan-swedan" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://wa.me/201515227612" target="_blank" rel="noreferrer">WhatsApp ↗</a></div><div><h4>Built around</h4><p>Learn · Build · Secure · Grow</p></div></footer><div className="footer" style={{display:'flex',padding:'18px 0',gridTemplateColumns:'none'}}><span>© 2026 Marwan Swedan. All rights reserved.</span></div></div></main>}
