import Image from 'next/image';
import Link from 'next/link';
import { session } from '@/lib/auth';
import db from '@/lib/db';
import CourseThumbnail from '@/app/components/CourseThumbnail';
import EliteHomeMotion from '@/app/components/EliteHomeMotion';

const roles=[['Jul 2026 — Present','Security Operations Center Analyst','Alignerr'],['Jul 2026 — Present','Information Security Intern','Commercial International Bank (CIB Egypt)'],['Jun 2026 — Present','Network Engineer (Contract)','Internet Society'],['Feb 2026 — Present','CTF Player & Digital Forensics Analyst','Information Technology Institute'],['Apr 2026 — Present','Founder & Chairman','Sudo Academy']];
const projects=[['Artifact Hunter','Digital Forensics','Python · FastAPI · Volatility · Wireshark'],['Smart Environmental Regulation & Embedded Robotic Platform','Embedded Systems','C++ · Embedded C · Arduino'],['Optimized Database Application Framework','Web Platform','JavaScript · SQL · HTML · CSS']];
const skills=['SOC Operations','Digital Forensics','Network Analysis','Threat Intelligence','Python · C++','SIEM / Wazuh'];

export default async function Home(){
 const user=await session();
 const courses=await db`select c.id,c.title,c.slug,c.description,c.category,c.level,c.duration_minutes,c.thumbnail_url,c.is_free,c.price,count(l.id)::int as lesson_count from courses c left join lessons l on l.course_id=c.id and l.published=true where c.published=true group by c.id order by c.created_at desc limit 4`;
 return <main className="eliteHome"><EliteHomeMotion/><div className="eliteNoise" aria-hidden="true"/>
 <header className="eliteHeader"><Link className="eliteBrand" href="/" aria-label="Marwan Swedan home"><span className="eliteBrandMark">MS</span><span><b>Marwan Swedan</b><small>Cybersecurity · Academy</small></span></Link><div className="eliteHeaderMeta"><span>CYBERSECURITY / SOC / FORENSICS</span><span className="eliteStatus"><i/> AVAILABLE FOR TECHNICAL WORK</span></div><button className="eliteMenuButton" data-menu-toggle aria-expanded="false" aria-controls="elite-menu"><span>Menu</span><span className="eliteMenuIcon"><i/><i/><i/></span></button></header>
 <aside className="eliteMenu" id="elite-menu" aria-hidden="true"><div className="eliteMenuBackdrop" data-menu-close/><div className="eliteMenuPanel"><div className="eliteMenuTop"><span>NAVIGATION</span><button data-menu-close aria-label="Close menu">Close <b>×</b></button></div><nav className="eliteMenuLinks"><Link href="/" data-menu-link><small>01</small><span>Home</span><b>↗</b></Link><Link href="/courses" data-menu-link><small>02</small><span>Academy</span><b>↗</b></Link><Link href="/paths" data-menu-link><small>03</small><span>Learning Paths</span><b>↗</b></Link><a href="#work" data-menu-link><small>04</small><span>Experience</span><b>↓</b></a><a href="#projects" data-menu-link><small>05</small><span>Projects</span><b>↓</b></a><a href="#about" data-menu-link><small>06</small><span>About</span><b>↓</b></a>{user&&<Link href="/dashboard" data-menu-link><small>07</small><span>Dashboard</span><b>↗</b></Link>}</nav><div className="eliteMenuFooter"><span>MARWAN SWEDAN / 2026</span><a href="https://www.linkedin.com/in/marwan-swedan" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></aside>
 <section className="eliteHero" id="about"><div className="eliteHeroCopy"><div className="eliteKicker"><span>01 / PROFILE</span><i/></div><h1>Security is<br/><em>built,</em> not assumed.</h1><p className="eliteHeroLead">Cybersecurity Analyst focused on Security Operations, digital forensics, network analysis and practical technical education.</p><div className="eliteHeroActions"><Link className="eliteButton eliteButtonPrimary" href="/courses" data-magnetic>Explore Academy <span>↗</span></Link><a className="eliteButton" href="#work" data-magnetic>View portfolio <span>↓</span></a></div><div className="eliteHeroFacts"><div><strong>TOP 27</strong><span>Egypt · Digital Forensics / CTF</span></div><div><strong>3.77 / 4.00</strong><span>Computer Science & AI · PUA</span></div><div><strong>150+</strong><span>Students mentored</span></div></div></div><div className="eliteHeroVisual"><div className="eliteOrb"/><div className="eliteGrid"/><div className="elitePortrait"><Image src="/images/profile.jpg" alt="Marwan Swedan" fill priority sizes="(max-width: 900px) 100vw, 48vw" style={{objectFit:'cover',objectPosition:'center 28%'}}/></div><div className="eliteVisualTag">MS / 26</div><div className="eliteVisualLine"/></div><div className="eliteScrollHint"><span>Scroll to explore</span><i/></div></section>
 <section className="eliteStatement"><div className="eliteSectionNumber">02</div><div className="eliteStatementText"><p>I work at the intersection of <strong>defensive security</strong>, investigation and education — turning complex technical problems into systems people can understand, test and improve.</p></div><div className="eliteStatementAside"><span>FOCUS</span><b>SOC · FORENSICS<br/>NETWORKS · EDUCATION</b></div></section>
 <section className="eliteAcademy" id="academy"><div className="eliteSectionHead"><div><div className="eliteKicker"><span>03 / ACADEMY</span><i/></div><h2>Learn by<br/><em>building.</em></h2></div><div className="eliteAcademySwitch"><Link className="active" href="/courses">Courses</Link><Link href="/paths">Learning Paths</Link></div></div><div className="eliteCourseGrid">{courses.map((c:any,i:number)=><Link className="eliteCourseCard" href={`/courses/${c.slug}`} key={c.id} data-tilt><div className="eliteCourseGlow"/><div className="eliteCourseImage"><CourseThumbnail src={c.thumbnail_url} category={c.category} alt={c.title}/><span>0{i+1}</span></div><div className="eliteCourseBody"><div><small>{c.category||'CYBERSECURITY'} · {c.level||'BEGINNER'}</small><h3>{c.title}</h3></div><div className="eliteCourseMeta"><span>{c.lesson_count} lessons</span><span>{c.is_free?'Free':`${Number(c.price||0).toLocaleString()} EGP`}</span><b>↗</b></div></div></Link>)}</div>{courses.length===0&&<div className="eliteEmpty">New courses are being prepared. Check the Academy soon.</div>}<div className="eliteAcademyCta"><span>COURSES + PATHS / PRACTICAL LEARNING</span><Link href="/courses">Enter the Academy <b>↗</b></Link></div></section>
 <section className="eliteWork" id="work"><div className="eliteSectionNumber">04</div><div className="eliteWorkHead"><div className="eliteKicker"><span>EXPERIENCE</span><i/></div><h2>Security work<br/>with <em>context.</em></h2><p>Current roles spanning SOC monitoring, information security, network engineering, digital forensics and technical leadership.</p></div><div className="eliteTimeline">{roles.map((r,i)=><article className="eliteRole" key={r[1]+r[2]}><time>0{i+1}<br/><span>{r[0]}</span></time><div><h3>{r[1]}</h3><p>{r[2]}</p></div><b>↗</b></article>)}</div></section>
 <section className="eliteProjects" id="projects"><div className="eliteSectionNumber">05</div><div className="eliteProjectsHead"><div className="eliteKicker"><span>SELECTED WORK</span><i/></div><h2>Built. Tested.<br/><em>Investigated.</em></h2></div><div className="eliteProjectGrid">{projects.map((p,i)=><article className="eliteProject" key={p[0]} data-tilt><span>0{i+1} / {p[1]}</span><h3>{p[0]}</h3><p>{p[2]}</p><b>↗</b></article>)}</div></section>
 <section className="eliteSkills"><div className="eliteSectionNumber">06</div><div><div className="eliteKicker"><span>TECHNICAL STACK</span><i/></div><h2>Tools for the<br/><em>defensive side.</em></h2></div><div className="eliteSkillList">{skills.map((skill,i)=><div key={skill}><span>0{i+1}</span><b>{skill}</b><i>↗</i></div>)}</div></section>
 <section className="eliteCta"><div className="eliteKicker"><span>07 / NEXT MOVE</span><i/></div><h2>Keep learning.<br/><em>Stay curious.</em></h2><p>Explore practical cybersecurity courses, learning paths and technical work.</p><div className="eliteHeroActions"><Link className="eliteButton eliteButtonPrimary" href="/courses" data-magnetic>Enter Academy <span>↗</span></Link><a className="eliteButton" href="https://www.linkedin.com/in/marwan-swedan" target="_blank" rel="noreferrer" data-magnetic>LinkedIn <span>↗</span></a></div></section>
 <footer className="eliteFooter"><div><Link className="eliteBrand" href="/"><span className="eliteBrandMark">MS</span><span><b>Marwan Swedan</b><small>Cybersecurity · Academy</small></span></Link><p>Cybersecurity · Digital Forensics · Security Operations · Education</p></div><div className="eliteFooterLinks"><span>EXPLORE</span><Link href="/courses">Academy</Link><Link href="/paths">Learning Paths</Link>{user&&<Link href="/dashboard">Dashboard</Link>}{user?.role==='admin'&&<Link href="/admin">Admin</Link>}</div><div className="eliteFooterLinks"><span>CONNECT</span><a href="https://www.linkedin.com/in/marwan-swedan" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://wa.me/201515227612" target="_blank" rel="noreferrer">WhatsApp ↗</a></div><div className="eliteFooterBottom"><span>© 2026 Marwan Swedan</span><span>Built for the defensive side.</span></div></footer>
 </main>;
}
