import {NextResponse} from 'next/server';
import db from '@/lib/db';
import {requireAdmin} from '@/lib/auth';
import {audit} from '@/lib/security';

function makeSlug(value:string){const base=value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');return base||`course-${Date.now()}`}
async function uniqueSlug(raw:string,id?:string){const base=makeSlug(raw);const rows=id?await db`select id from courses where slug=${base} and id<>${id} limit 1`:await db`select id from courses where slug=${base} limit 1`;return rows.length?`${base}-${Date.now().toString().slice(-6)}`:base}

export async function GET(){try{await requireAdmin();return NextResponse.json({courses:await db`select * from courses order by created_at desc`})}catch(e:any){return NextResponse.json({error:e.message==='FORBIDDEN'?'Forbidden':'Authentication required'},{status:e.message==='FORBIDDEN'?403:401})}}

export async function POST(request:Request){try{const admin=await requireAdmin();const b=await request.json();const title=String(b.title||'Untitled Course').trim()||'Untitled Course';const slug=await uniqueSlug(String(b.slug||title));const description=String(b.description||'').trim();const category=String(b.category||'Cybersecurity').trim()||'Cybersecurity';const level=String(b.level||'Beginner').trim()||'Beginner';const duration=Math.max(0,Number(b.durationMinutes||0));const isFree=Boolean(b.isFree);const price=isFree?0:Math.max(0,Number(b.price||0));const rows=await db`insert into courses(title,slug,description,category,level,duration_minutes,thumbnail_url,ai_context,is_free,price,published) values(${title},${slug},${description},${category},${level},${duration},${b.thumbnailUrl||null},${b.aiContext||''},${isFree},${price},${Boolean(b.published)}) returning *`;await audit(admin.id,'create_course',request,{courseId:rows[0].id});return NextResponse.json({course:rows[0]},{status:201})}catch(e:any){console.error('CREATE_COURSE_FAILED',e);return NextResponse.json({error:e.message==='FORBIDDEN'?'Forbidden':'Could not create course'},{status:e.message==='FORBIDDEN'?403:400})}}

export async function PUT(request:Request){try{const admin=await requireAdmin();const b=await request.json();const id=String(b.id||'');if(!id)return NextResponse.json({error:'Course id is required.'},{status:400});const title=String(b.title||'Untitled Course').trim()||'Untitled Course';const slug=await uniqueSlug(String(b.slug||title),id);const isFree=Boolean(b.isFree),price=isFree?0:Math.max(0,Number(b.price||0));const rows=await db`update courses set title=${title},slug=${slug},description=${String(b.description||'')},category=${String(b.category||'Cybersecurity')},level=${String(b.level||'Beginner')},duration_minutes=${Math.max(0,Number(b.durationMinutes||0))},thumbnail_url=${b.thumbnailUrl||null},ai_context=${b.aiContext||''},is_free=${isFree},price=${price},published=${Boolean(b.published)},updated_at=now() where id=${id} returning *`;if(!rows.length)return NextResponse.json({error:'Course not found'},{status:404});await audit(admin.id,'update_course',request,{courseId:id});return NextResponse.json({course:rows[0]})}catch(e:any){console.error('UPDATE_COURSE_FAILED',e);return NextResponse.json({error:e.message==='FORBIDDEN'?'Forbidden':'Could not update course'},{status:e.message==='FORBIDDEN'?403:400})}}

export async function DELETE(request:Request){try{const admin=await requireAdmin();const {id}=await request.json();await db`delete from courses where id=${id}`;await audit(admin.id,'delete_course',request,{courseId:id});return NextResponse.json({ok:true})}catch(e:any){return NextResponse.json({error:e.message==='FORBIDDEN'?'Forbidden':'Could not delete course'},{status:e.message==='FORBIDDEN'?403:400})}}
