create extension if not exists pgcrypto;
create table if not exists users(id uuid primary key default gen_random_uuid(),name text not null,email text not null unique,whatsapp text not null,username text not null unique,password_hash text not null,role text not null default 'student' check(role in('student','admin')),is_blocked boolean not null default false,blocked_until timestamptz,bio text not null default '',avatar_url text,cv_url text,cv_name text,created_at timestamptz not null default now(),last_login_at timestamptz,username_updated_at timestamptz,password_change_allowed boolean not null default false);
create table if not exists courses(id uuid primary key default gen_random_uuid(),title text not null default 'Untitled Course',slug text not null unique,description text not null default '',category text not null default 'Cybersecurity',level text not null default 'Beginner',duration_minutes integer not null default 0,thumbnail_url text,ai_context text not null default '',is_free boolean not null default true,price numeric(10,2) not null default 0,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table users add column if not exists username_updated_at timestamptz;
alter table users add column if not exists bio text not null default '';
alter table users add column if not exists avatar_url text;
alter table users add column if not exists cv_url text;
alter table users add column if not exists cv_name text;
alter table users add column if not exists password_change_allowed boolean not null default false;
alter table courses add column if not exists is_free boolean not null default true;
alter table courses add column if not exists price numeric(10,2) not null default 0;
alter table courses alter column title set default 'Untitled Course';
alter table courses alter column description set default '';
alter table courses alter column category set default 'Cybersecurity';
alter table courses alter column level set default 'Beginner';
create table if not exists lessons(id uuid primary key default gen_random_uuid(),course_id uuid not null references courses(id) on delete cascade,title text not null,slug text not null,position integer not null default 0,duration_minutes integer not null default 0,video_url text,content text not null default '',published boolean not null default false,unique(course_id,slug));
alter table lessons add column if not exists file_url text;
alter table lessons add column if not exists file_name text;
create table if not exists enrollments(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,course_id uuid not null references courses(id) on delete cascade,granted_by uuid references users(id),created_at timestamptz not null default now(),revoked_at timestamptz,unique(user_id,course_id));
create table if not exists lesson_progress(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,lesson_id uuid not null references lessons(id) on delete cascade,completed boolean not null default false,updated_at timestamptz not null default now(),unique(user_id,lesson_id));
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid references users(id) on delete set null,action text not null,ip text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists security_events(id uuid primary key default gen_random_uuid(),user_id uuid references users(id) on delete set null,event_type text not null,severity text not null default 'medium',ip text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists otp_challenges(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,purpose text not null check(purpose in('login','password_reset','password_change','email_change')),code_hash text not null,expires_at timestamptz not null,attempts integer not null default 0,consumed_at timestamptz,created_at timestamptz not null default now());
create table if not exists trusted_devices(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,token_hash text not null unique,expires_at timestamptz not null,created_at timestamptz not null default now(),last_used_at timestamptz);
create table if not exists admin_login_links(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,token_hash text not null unique,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now());
create index if not exists audit_logs_user_idx on audit_logs(user_id,created_at desc);
create index if not exists security_events_user_idx on security_events(user_id,created_at desc);
create index if not exists enrollments_user_idx on enrollments(user_id,revoked_at);
create index if not exists otp_challenges_user_idx on otp_challenges(user_id,purpose,created_at desc);
create index if not exists trusted_devices_user_idx on trusted_devices(user_id,expires_at);
create index if not exists admin_login_links_user_idx on admin_login_links(user_id,expires_at,used_at);
alter table lesson_progress add column if not exists progress_seconds integer not null default 0;
alter table lesson_progress add column if not exists last_viewed_at timestamptz;
create index if not exists lesson_progress_user_idx on lesson_progress(user_id,updated_at desc);
